// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPIStocksQueryStockReader is a Reader for the GetStocksmithAPIStocksQueryStock structure.
type GetStocksmithAPIStocksQueryStockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksmithAPIStocksQueryStockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksmithAPIStocksQueryStockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksmithAPIStocksQueryStockOK creates a GetStocksmithAPIStocksQueryStockOK with default headers values
func NewGetStocksmithAPIStocksQueryStockOK() *GetStocksmithAPIStocksQueryStockOK {
	return &GetStocksmithAPIStocksQueryStockOK{}
}

/*GetStocksmithAPIStocksQueryStockOK handles this case with default header values.

Successful Stock Query
*/
type GetStocksmithAPIStocksQueryStockOK struct {
	Payload []*models.StockData
}

func (o *GetStocksmithAPIStocksQueryStockOK) Error() string {
	return fmt.Sprintf("[GET /stocksmith/api/stocks/queryStock][%d] getStocksmithApiStocksQueryStockOK  %+v", 200, o.Payload)
}

func (o *GetStocksmithAPIStocksQueryStockOK) GetPayload() []*models.StockData {
	return o.Payload
}

func (o *GetStocksmithAPIStocksQueryStockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
