// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPIStocksQueryTopReader is a Reader for the GetStocksmithAPIStocksQueryTop structure.
type GetStocksmithAPIStocksQueryTopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksmithAPIStocksQueryTopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksmithAPIStocksQueryTopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksmithAPIStocksQueryTopOK creates a GetStocksmithAPIStocksQueryTopOK with default headers values
func NewGetStocksmithAPIStocksQueryTopOK() *GetStocksmithAPIStocksQueryTopOK {
	return &GetStocksmithAPIStocksQueryTopOK{}
}

/*GetStocksmithAPIStocksQueryTopOK handles this case with default header values.

Successful Stock Query
*/
type GetStocksmithAPIStocksQueryTopOK struct {
	Payload []*models.StockData
}

func (o *GetStocksmithAPIStocksQueryTopOK) Error() string {
	return fmt.Sprintf("[GET /stocksmith/api/stocks/queryTop][%d] getStocksmithApiStocksQueryTopOK  %+v", 200, o.Payload)
}

func (o *GetStocksmithAPIStocksQueryTopOK) GetPayload() []*models.StockData {
	return o.Payload
}

func (o *GetStocksmithAPIStocksQueryTopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
