// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStocksQueryTopParams creates a new GetStocksQueryTopParams object
// with the default values initialized.
func NewGetStocksQueryTopParams() *GetStocksQueryTopParams {

	return &GetStocksQueryTopParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksQueryTopParamsWithTimeout creates a new GetStocksQueryTopParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksQueryTopParamsWithTimeout(timeout time.Duration) *GetStocksQueryTopParams {

	return &GetStocksQueryTopParams{

		timeout: timeout,
	}
}

// NewGetStocksQueryTopParamsWithContext creates a new GetStocksQueryTopParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksQueryTopParamsWithContext(ctx context.Context) *GetStocksQueryTopParams {

	return &GetStocksQueryTopParams{

		Context: ctx,
	}
}

// NewGetStocksQueryTopParamsWithHTTPClient creates a new GetStocksQueryTopParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksQueryTopParamsWithHTTPClient(client *http.Client) *GetStocksQueryTopParams {

	return &GetStocksQueryTopParams{
		HTTPClient: client,
	}
}

/*GetStocksQueryTopParams contains all the parameters to send to the API endpoint
for the get stocks query top operation typically these are written to a http.Request
*/
type GetStocksQueryTopParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocks query top params
func (o *GetStocksQueryTopParams) WithTimeout(timeout time.Duration) *GetStocksQueryTopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocks query top params
func (o *GetStocksQueryTopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocks query top params
func (o *GetStocksQueryTopParams) WithContext(ctx context.Context) *GetStocksQueryTopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocks query top params
func (o *GetStocksQueryTopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocks query top params
func (o *GetStocksQueryTopParams) WithHTTPClient(client *http.Client) *GetStocksQueryTopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocks query top params
func (o *GetStocksQueryTopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksQueryTopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
