// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/client/models"
)

// GetStocksQueryTopReader is a Reader for the GetStocksQueryTop structure.
type GetStocksQueryTopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksQueryTopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksQueryTopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksQueryTopOK creates a GetStocksQueryTopOK with default headers values
func NewGetStocksQueryTopOK() *GetStocksQueryTopOK {
	return &GetStocksQueryTopOK{}
}

/*GetStocksQueryTopOK handles this case with default header values.

Successful Stock Query
*/
type GetStocksQueryTopOK struct {
	Payload []*models.NewsResponse
}

func (o *GetStocksQueryTopOK) Error() string {
	return fmt.Sprintf("[GET /stocks/queryTop][%d] getStocksQueryTopOK  %+v", 200, o.Payload)
}

func (o *GetStocksQueryTopOK) GetPayload() []*models.NewsResponse {
	return o.Payload
}

func (o *GetStocksQueryTopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
