// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/client/models"
)

// GetStocksQueryStockReader is a Reader for the GetStocksQueryStock structure.
type GetStocksQueryStockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksQueryStockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksQueryStockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksQueryStockOK creates a GetStocksQueryStockOK with default headers values
func NewGetStocksQueryStockOK() *GetStocksQueryStockOK {
	return &GetStocksQueryStockOK{}
}

/*GetStocksQueryStockOK handles this case with default header values.

Successful Stock Query
*/
type GetStocksQueryStockOK struct {
	Payload []*models.StockData
}

func (o *GetStocksQueryStockOK) Error() string {
	return fmt.Sprintf("[GET /stocks/queryStock][%d] getStocksQueryStockOK  %+v", 200, o.Payload)
}

func (o *GetStocksQueryStockOK) GetPayload() []*models.StockData {
	return o.Payload
}

func (o *GetStocksQueryStockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
