// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStocksQueryStockParams creates a new GetStocksQueryStockParams object
// with the default values initialized.
func NewGetStocksQueryStockParams() *GetStocksQueryStockParams {

	return &GetStocksQueryStockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksQueryStockParamsWithTimeout creates a new GetStocksQueryStockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksQueryStockParamsWithTimeout(timeout time.Duration) *GetStocksQueryStockParams {

	return &GetStocksQueryStockParams{

		timeout: timeout,
	}
}

// NewGetStocksQueryStockParamsWithContext creates a new GetStocksQueryStockParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksQueryStockParamsWithContext(ctx context.Context) *GetStocksQueryStockParams {

	return &GetStocksQueryStockParams{

		Context: ctx,
	}
}

// NewGetStocksQueryStockParamsWithHTTPClient creates a new GetStocksQueryStockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksQueryStockParamsWithHTTPClient(client *http.Client) *GetStocksQueryStockParams {

	return &GetStocksQueryStockParams{
		HTTPClient: client,
	}
}

/*GetStocksQueryStockParams contains all the parameters to send to the API endpoint
for the get stocks query stock operation typically these are written to a http.Request
*/
type GetStocksQueryStockParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocks query stock params
func (o *GetStocksQueryStockParams) WithTimeout(timeout time.Duration) *GetStocksQueryStockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocks query stock params
func (o *GetStocksQueryStockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocks query stock params
func (o *GetStocksQueryStockParams) WithContext(ctx context.Context) *GetStocksQueryStockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocks query stock params
func (o *GetStocksQueryStockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocks query stock params
func (o *GetStocksQueryStockParams) WithHTTPClient(client *http.Client) *GetStocksQueryStockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocks query stock params
func (o *GetStocksQueryStockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksQueryStockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
