// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewsRequest NewsRequest
//
// Request to News API for news articles
//
// swagger:model NewsRequest
type NewsRequest struct {

	// num response
	NumResponse int32 `json:"NumResponse,omitempty"`

	// query body
	QueryBody string `json:"QueryBody,omitempty"`

	// query type
	QueryType string `json:"QueryType,omitempty"`

	// sources list
	SourcesList []string `json:"SourcesList"`
}

// Validate validates this news request
func (m *NewsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewsRequest) UnmarshalBinary(b []byte) error {
	var res NewsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
