// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPIStocksQueryStockOKCode is the HTTP code returned for type GetStocksmithAPIStocksQueryStockOK
const GetStocksmithAPIStocksQueryStockOKCode int = 200

/*GetStocksmithAPIStocksQueryStockOK Successful Stock Query

swagger:response getStocksmithApiStocksQueryStockOK
*/
type GetStocksmithAPIStocksQueryStockOK struct {

	/*
	  In: Body
	*/
	Payload []*models.StockData `json:"body,omitempty"`
}

// NewGetStocksmithAPIStocksQueryStockOK creates GetStocksmithAPIStocksQueryStockOK with default headers values
func NewGetStocksmithAPIStocksQueryStockOK() *GetStocksmithAPIStocksQueryStockOK {

	return &GetStocksmithAPIStocksQueryStockOK{}
}

// WithPayload adds the payload to the get stocksmith Api stocks query stock o k response
func (o *GetStocksmithAPIStocksQueryStockOK) WithPayload(payload []*models.StockData) *GetStocksmithAPIStocksQueryStockOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stocksmith Api stocks query stock o k response
func (o *GetStocksmithAPIStocksQueryStockOK) SetPayload(payload []*models.StockData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStocksmithAPIStocksQueryStockOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.StockData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
