// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPIStocksQueryTopOKCode is the HTTP code returned for type GetStocksmithAPIStocksQueryTopOK
const GetStocksmithAPIStocksQueryTopOKCode int = 200

/*GetStocksmithAPIStocksQueryTopOK Successful Stock Query

swagger:response getStocksmithApiStocksQueryTopOK
*/
type GetStocksmithAPIStocksQueryTopOK struct {

	/*
	  In: Body
	*/
	Payload []*models.StockData `json:"body,omitempty"`
}

// NewGetStocksmithAPIStocksQueryTopOK creates GetStocksmithAPIStocksQueryTopOK with default headers values
func NewGetStocksmithAPIStocksQueryTopOK() *GetStocksmithAPIStocksQueryTopOK {

	return &GetStocksmithAPIStocksQueryTopOK{}
}

// WithPayload adds the payload to the get stocksmith Api stocks query top o k response
func (o *GetStocksmithAPIStocksQueryTopOK) WithPayload(payload []*models.StockData) *GetStocksmithAPIStocksQueryTopOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stocksmith Api stocks query top o k response
func (o *GetStocksmithAPIStocksQueryTopOK) SetPayload(payload []*models.StockData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStocksmithAPIStocksQueryTopOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.StockData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
