// Code generated by go-swagger; DO NOT EDIT.

package stock_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStocksmithAPIStocksQueryTopHandlerFunc turns a function with the right signature into a get stocksmith API stocks query top handler
type GetStocksmithAPIStocksQueryTopHandlerFunc func(GetStocksmithAPIStocksQueryTopParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStocksmithAPIStocksQueryTopHandlerFunc) Handle(params GetStocksmithAPIStocksQueryTopParams) middleware.Responder {
	return fn(params)
}

// GetStocksmithAPIStocksQueryTopHandler interface for that can handle valid get stocksmith API stocks query top params
type GetStocksmithAPIStocksQueryTopHandler interface {
	Handle(GetStocksmithAPIStocksQueryTopParams) middleware.Responder
}

// NewGetStocksmithAPIStocksQueryTop creates a new http.Handler for the get stocksmith API stocks query top operation
func NewGetStocksmithAPIStocksQueryTop(ctx *middleware.Context, handler GetStocksmithAPIStocksQueryTopHandler) *GetStocksmithAPIStocksQueryTop {
	return &GetStocksmithAPIStocksQueryTop{Context: ctx, Handler: handler}
}

/*GetStocksmithAPIStocksQueryTop swagger:route GET /stocksmith/api/stocks/queryTop Stock API getStocksmithApiStocksQueryTop

Querys information about the top N stocks

Querys information about the top N stocks

*/
type GetStocksmithAPIStocksQueryTop struct {
	Context *middleware.Context
	Handler GetStocksmithAPIStocksQueryTopHandler
}

func (o *GetStocksmithAPIStocksQueryTop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStocksmithAPIStocksQueryTopParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
