// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPINewsQueryReader is a Reader for the GetStocksmithAPINewsQuery structure.
type GetStocksmithAPINewsQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksmithAPINewsQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksmithAPINewsQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksmithAPINewsQueryOK creates a GetStocksmithAPINewsQueryOK with default headers values
func NewGetStocksmithAPINewsQueryOK() *GetStocksmithAPINewsQueryOK {
	return &GetStocksmithAPINewsQueryOK{}
}

/*GetStocksmithAPINewsQueryOK handles this case with default header values.

Successful Query
*/
type GetStocksmithAPINewsQueryOK struct {
	Payload *models.NewsResponse
}

func (o *GetStocksmithAPINewsQueryOK) Error() string {
	return fmt.Sprintf("[GET /stocksmith/api/news/query][%d] getStocksmithApiNewsQueryOK  %+v", 200, o.Payload)
}

func (o *GetStocksmithAPINewsQueryOK) GetPayload() *models.NewsResponse {
	return o.Payload
}

func (o *GetStocksmithAPINewsQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
