// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// NewGetStocksmithAPINewsQueryParams creates a new GetStocksmithAPINewsQueryParams object
// with the default values initialized.
func NewGetStocksmithAPINewsQueryParams() *GetStocksmithAPINewsQueryParams {
	var ()
	return &GetStocksmithAPINewsQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksmithAPINewsQueryParamsWithTimeout creates a new GetStocksmithAPINewsQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksmithAPINewsQueryParamsWithTimeout(timeout time.Duration) *GetStocksmithAPINewsQueryParams {
	var ()
	return &GetStocksmithAPINewsQueryParams{

		timeout: timeout,
	}
}

// NewGetStocksmithAPINewsQueryParamsWithContext creates a new GetStocksmithAPINewsQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksmithAPINewsQueryParamsWithContext(ctx context.Context) *GetStocksmithAPINewsQueryParams {
	var ()
	return &GetStocksmithAPINewsQueryParams{

		Context: ctx,
	}
}

// NewGetStocksmithAPINewsQueryParamsWithHTTPClient creates a new GetStocksmithAPINewsQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksmithAPINewsQueryParamsWithHTTPClient(client *http.Client) *GetStocksmithAPINewsQueryParams {
	var ()
	return &GetStocksmithAPINewsQueryParams{
		HTTPClient: client,
	}
}

/*GetStocksmithAPINewsQueryParams contains all the parameters to send to the API endpoint
for the get stocksmith API news query operation typically these are written to a http.Request
*/
type GetStocksmithAPINewsQueryParams struct {

	/*Body
	  Request for news query

	*/
	Body *models.NewsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) WithTimeout(timeout time.Duration) *GetStocksmithAPINewsQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) WithContext(ctx context.Context) *GetStocksmithAPINewsQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) WithHTTPClient(client *http.Client) *GetStocksmithAPINewsQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) WithBody(body *models.NewsRequest) *GetStocksmithAPINewsQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get stocksmith API news query params
func (o *GetStocksmithAPINewsQueryParams) SetBody(body *models.NewsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksmithAPINewsQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
