// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"pkg/server/models"
)

// PostNewsQueryOKCode is the HTTP code returned for type PostNewsQueryOK
const PostNewsQueryOKCode int = 200

/*PostNewsQueryOK Successful Query

swagger:response postNewsQueryOK
*/
type PostNewsQueryOK struct {

	/*
	  In: Body
	*/
	Payload *models.NewsResponse `json:"body,omitempty"`
}

// NewPostNewsQueryOK creates PostNewsQueryOK with default headers values
func NewPostNewsQueryOK() *PostNewsQueryOK {

	return &PostNewsQueryOK{}
}

// WithPayload adds the payload to the post news query o k response
func (o *PostNewsQueryOK) WithPayload(payload *models.NewsResponse) *PostNewsQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post news query o k response
func (o *PostNewsQueryOK) SetPayload(payload *models.NewsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNewsQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
