// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/client/models"
)

// PostNewsQueryReader is a Reader for the PostNewsQuery structure.
type PostNewsQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostNewsQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostNewsQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostNewsQueryOK creates a PostNewsQueryOK with default headers values
func NewPostNewsQueryOK() *PostNewsQueryOK {
	return &PostNewsQueryOK{}
}

/*PostNewsQueryOK handles this case with default header values.

Successful Query
*/
type PostNewsQueryOK struct {
	Payload *models.NewsResponse
}

func (o *PostNewsQueryOK) Error() string {
	return fmt.Sprintf("[POST /news/query][%d] postNewsQueryOK  %+v", 200, o.Payload)
}

func (o *PostNewsQueryOK) GetPayload() *models.NewsResponse {
	return o.Payload
}

func (o *PostNewsQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
