// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/client/models"
)

// NewPostNewsQueryParams creates a new PostNewsQueryParams object
// with the default values initialized.
func NewPostNewsQueryParams() *PostNewsQueryParams {
	var ()
	return &PostNewsQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostNewsQueryParamsWithTimeout creates a new PostNewsQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostNewsQueryParamsWithTimeout(timeout time.Duration) *PostNewsQueryParams {
	var ()
	return &PostNewsQueryParams{

		timeout: timeout,
	}
}

// NewPostNewsQueryParamsWithContext creates a new PostNewsQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostNewsQueryParamsWithContext(ctx context.Context) *PostNewsQueryParams {
	var ()
	return &PostNewsQueryParams{

		Context: ctx,
	}
}

// NewPostNewsQueryParamsWithHTTPClient creates a new PostNewsQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostNewsQueryParamsWithHTTPClient(client *http.Client) *PostNewsQueryParams {
	var ()
	return &PostNewsQueryParams{
		HTTPClient: client,
	}
}

/*PostNewsQueryParams contains all the parameters to send to the API endpoint
for the post news query operation typically these are written to a http.Request
*/
type PostNewsQueryParams struct {

	/*Body
	  Request for news query

	*/
	Body *models.NewsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post news query params
func (o *PostNewsQueryParams) WithTimeout(timeout time.Duration) *PostNewsQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post news query params
func (o *PostNewsQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post news query params
func (o *PostNewsQueryParams) WithContext(ctx context.Context) *PostNewsQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post news query params
func (o *PostNewsQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post news query params
func (o *PostNewsQueryParams) WithHTTPClient(client *http.Client) *PostNewsQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post news query params
func (o *PostNewsQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post news query params
func (o *PostNewsQueryParams) WithBody(body *models.NewsRequest) *PostNewsQueryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post news query params
func (o *PostNewsQueryParams) SetBody(body *models.NewsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostNewsQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
