// Code generated by go-swagger; DO NOT EDIT.

// Package restapi StockSmith Microservices
//
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact:
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
