// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "StockSmith Microservices",
    "contact": {},
    "version": "1.0.0"
  },
  "paths": {
    "/news/query": {
      "post": {
        "description": "Retrieves a news query",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "News API"
        ],
        "summary": "Retrieves a news query",
        "parameters": [
          {
            "description": "Request for news query",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Query",
            "schema": {
              "$ref": "#/definitions/NewsResponse"
            }
          }
        }
      }
    },
    "/stocks/queryStock": {
      "get": {
        "description": "Querys information about a specific stock",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Stock API"
        ],
        "summary": "Querys information about a specific stock",
        "responses": {
          "200": {
            "description": "Successful Stock Query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/StockData"
              }
            }
          }
        }
      }
    },
    "/stocks/queryTop": {
      "get": {
        "description": "Querys information about the top N stocks",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Stock API"
        ],
        "summary": "Querys information about the top N stocks",
        "responses": {
          "200": {
            "description": "Successful Stock Query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/NewsResponse"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NewsRequest": {
      "description": "Request to News API for news articles",
      "type": "object",
      "title": "NewsRequest",
      "properties": {
        "NumResponse": {
          "type": "integer",
          "format": "int32",
          "example": 2
        },
        "QueryBody": {
          "type": "string",
          "example": "NVDA"
        },
        "QueryType": {
          "type": "string",
          "example": "Ticker"
        },
        "SourcesList": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "CNN",
            "Yahoo News"
          ]
        }
      }
    },
    "NewsResponse": {
      "description": "Response to News API for news articles",
      "type": "object",
      "title": "NewsResponse",
      "properties": {
        "ArticleList": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://www.CNN.com/article1",
            "https://www.yahoo.com/news/article2"
          ]
        }
      }
    },
    "StockData": {
      "description": "Object to hold serialized stock data",
      "type": "object",
      "title": "StockData",
      "properties": {
        "ShareValue": {
          "type": "integer",
          "format": "int32",
          "example": 263
        }
      }
    }
  },
  "tags": [
    {
      "description": "API for retrieving news",
      "name": "News API"
    },
    {
      "description": "API for retrieving stock data",
      "name": "Stock API"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "StockSmith Microservices",
    "contact": {},
    "version": "1.0.0"
  },
  "paths": {
    "/news/query": {
      "post": {
        "description": "Retrieves a news query",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "News API"
        ],
        "summary": "Retrieves a news query",
        "parameters": [
          {
            "description": "Request for news query",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Query",
            "schema": {
              "$ref": "#/definitions/NewsResponse"
            }
          }
        }
      }
    },
    "/stocks/queryStock": {
      "get": {
        "description": "Querys information about a specific stock",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Stock API"
        ],
        "summary": "Querys information about a specific stock",
        "responses": {
          "200": {
            "description": "Successful Stock Query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/StockData"
              }
            }
          }
        }
      }
    },
    "/stocks/queryTop": {
      "get": {
        "description": "Querys information about the top N stocks",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Stock API"
        ],
        "summary": "Querys information about the top N stocks",
        "responses": {
          "200": {
            "description": "Successful Stock Query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/NewsResponse"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NewsRequest": {
      "description": "Request to News API for news articles",
      "type": "object",
      "title": "NewsRequest",
      "properties": {
        "NumResponse": {
          "type": "integer",
          "format": "int32",
          "example": 2
        },
        "QueryBody": {
          "type": "string",
          "example": "NVDA"
        },
        "QueryType": {
          "type": "string",
          "example": "Ticker"
        },
        "SourcesList": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "CNN",
            "Yahoo News"
          ]
        }
      }
    },
    "NewsResponse": {
      "description": "Response to News API for news articles",
      "type": "object",
      "title": "NewsResponse",
      "properties": {
        "ArticleList": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://www.CNN.com/article1",
            "https://www.yahoo.com/news/article2"
          ]
        }
      }
    },
    "StockData": {
      "description": "Object to hold serialized stock data",
      "type": "object",
      "title": "StockData",
      "properties": {
        "ShareValue": {
          "type": "integer",
          "format": "int32",
          "example": 263
        }
      }
    }
  },
  "tags": [
    {
      "description": "API for retrieving news",
      "name": "News API"
    },
    {
      "description": "API for retrieving stock data",
      "name": "Stock API"
    }
  ]
}`))
}
