// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/stocksmith/stockadvisor-web-app/back-end/pkg/models"
)

// GetStocksmithAPINewsQueryOKCode is the HTTP code returned for type GetStocksmithAPINewsQueryOK
const GetStocksmithAPINewsQueryOKCode int = 200

/*GetStocksmithAPINewsQueryOK Successful Query

swagger:response getStocksmithApiNewsQueryOK
*/
type GetStocksmithAPINewsQueryOK struct {

	/*
	  In: Body
	*/
	Payload *models.NewsResponse `json:"body,omitempty"`
}

// NewGetStocksmithAPINewsQueryOK creates GetStocksmithAPINewsQueryOK with default headers values
func NewGetStocksmithAPINewsQueryOK() *GetStocksmithAPINewsQueryOK {

	return &GetStocksmithAPINewsQueryOK{}
}

// WithPayload adds the payload to the get stocksmith Api news query o k response
func (o *GetStocksmithAPINewsQueryOK) WithPayload(payload *models.NewsResponse) *GetStocksmithAPINewsQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stocksmith Api news query o k response
func (o *GetStocksmithAPINewsQueryOK) SetPayload(payload *models.NewsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStocksmithAPINewsQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
