// Code generated by go-swagger; DO NOT EDIT.

package news_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStocksmithAPINewsQueryHandlerFunc turns a function with the right signature into a get stocksmith API news query handler
type GetStocksmithAPINewsQueryHandlerFunc func(GetStocksmithAPINewsQueryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStocksmithAPINewsQueryHandlerFunc) Handle(params GetStocksmithAPINewsQueryParams) middleware.Responder {
	return fn(params)
}

// GetStocksmithAPINewsQueryHandler interface for that can handle valid get stocksmith API news query params
type GetStocksmithAPINewsQueryHandler interface {
	Handle(GetStocksmithAPINewsQueryParams) middleware.Responder
}

// NewGetStocksmithAPINewsQuery creates a new http.Handler for the get stocksmith API news query operation
func NewGetStocksmithAPINewsQuery(ctx *middleware.Context, handler GetStocksmithAPINewsQueryHandler) *GetStocksmithAPINewsQuery {
	return &GetStocksmithAPINewsQuery{Context: ctx, Handler: handler}
}

/*GetStocksmithAPINewsQuery swagger:route GET /stocksmith/api/news/query News API getStocksmithApiNewsQuery

Retrieves a news query

Retrieves a news query

*/
type GetStocksmithAPINewsQuery struct {
	Context *middleware.Context
	Handler GetStocksmithAPINewsQueryHandler
}

func (o *GetStocksmithAPINewsQuery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStocksmithAPINewsQueryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
